---
- name: Manage Kubernetes' Docker images

  hosts: kube-nodes

  - name: Setup Docker Inseure Registry
    lineinfile:
      path: /etc/sysconfig/docker
      regexp: '^ADD_REGISTRY='
      line: ADD_REGISTRY='--add-registry {{ satellite_host }}:5000'
    when: satellite_host != ''

  - name: Pull Kubernetes Docker Images
    docker_image:
      name: '{{ item }}'
    with_items: '{{ kube_images }}'
