---
- name: Manage ETCD Discovery Token

  hosts: bastion

  tasks:

  - name: Check ETCD discovery token file already exists
    stat:
      path: '{{ etcd_guid_file }}'
    register: etcd_needs_guid

  - name: Get ETCD discovery token
    get_url:
      dest: '{{ etcd_guid_file }}'
      url: 'https://discovery.etcd.io/new?size=3'
    when: etcd_needs_guid.stat.exists == False
