---
- name: Cleanup Kubernetes

  hosts: kube

  tasks:

  - name: Stop Kubernetes services
    systemd:
      state: stopped
      name: '{{ item }}'
      enabled: false
    with_items:
    - etcd3
    - flanneld
    - kubelet
    - kube-proxy
    when: inventory_hostname in groups['kube-nodes']

  - name: Create Kubernetes Manifest Folder
    file: 
      path: '{{ manifest_dir }}'
      state: absent
    when: inventory_hostname in groups['kube-nodes']

  - name: Remove previosly created containers
    shell: |
      docker kill $(docker ps -aq) || true
      docker rm $(docker ps -aq) || true
    when: inventory_hostname in groups['kube-nodes']

  - name: Remove SELinux context
    sefcontext:
      target: '{{ item }}(/.*)?'
      setype: '{{ etcd_selinux }}'
      state: absent
    with_items:
    - '{{ etc_data }}'
    when: inventory_hostname in groups['kube-nodes']

  - name: Remove ETCD data content
    file:
      path: '{{ etc_data }}'
      state: absent
    when: inventory_hostname in groups['kube-nodes']

  - name: Remove ETCD Discovery Token File
    file:
      path: '{{ etcd_guid_file }}'
      state: absent
    when: inventory_hostname in groups['bastion']
