---
- name: Setup kubernetes
  hosts: kube-nodes

  vars:
    pod_ext: "yaml"

  tasks:

  - name: Start and Enable FlannelD Services
    systemd:
      name: flanneld
      daemon_reload: yes
      enabled: true
      state: started

  - name: Restart Docker Service
    systemd:
      name: docker
      state: restarted

  - name: Create Kubernetes Manifest Folder
    file: 
      path: '{{ manifest_dir }}'
      state: directory

  - name: Copy Pod Description
    copy:
      src: 'files/{{ item }}.{{ pod_ext}}'
      dest: '{{ manifest_dir }}'
    with_items:
    - apiserver-pod
    - controller-mgr-pod
    - scheduler-pod

  - name: Copy Kubernetes config files
    template:
      src: 'files/{{ item }}.j2'
      dest: '{{ manifest_dir }}/../kubelet'
    with_items:
    - kubelet

  - name: Copy FlannelD Config
    template:
      src: 'files/{{ item }}.j2'
      dest: '/etc/sysconfig/{{ item }}'
    with_items:
    - flanneld

  - name: Start and Enable Services
    systemd:
      name: '{{ item }}'
      state: started
      enabled: true
    with_items:
    - kubelet
    - kube-proxy
