#---
- name: Setup kubernetes
  hosts: master-client
  
  vars:
    flanneld_config: flanneld-config.json

  tasks:

#  - name: Waiting for ETCD started up
#    uri:
#      url: http://{{ ansible_host }}:2379/v2/keys/
#      status_code: 200
#    register: result
#    until: result.status == 200
#    retries: 60
#    delay: 10

  - name: Waiting for ETCD health become good
    command: /usr/bin/etcdctl cluster-health
    register: result
    until: result.rc == 0
    retries: 60
    delay: 10

  - name: Warming up ETCD cluster
    pause:
      seconds: 10

  - name: Copy FlannelD config
    copy:
      src: 'files/{{ flanneld_config }}'
      dest: /tmp

  - name: Put FlannelD config to ETCD
    command: |
      curl -L 'http://{{ ansible_host }}:2379/v2/keys/{{ flannel_key }}/config' -XPUT --data-urlencode value@/tmp/{{ flanneld_config }}

  - name: Get FlannelD config from ETCD
    uri:
      url: 'http://{{ ansible_host }}:2379/v2/keys/{{ flannel_key }}/config'
    register: res
#  - debug: var=res
