---
- name: Create an RHV based VM
  hosts: bastion
  gather_facts: false

  vars_prompt:
    - name: 'username'
      prompt: 'Enter RHEV-M username'
      private: no
      default: dsevosty@idm01.srv.local
    - name: 'virt_provider_cluster'
      private: no
      default: 'RH-DEMO-01'
    - name: 'password'
      prompt: 'Enter RHEV-M users password'
      private: yes

  tasks:
  - name: Download Virtual provider SSL cert
    get_url:
      url: 'http://{{ virt_provider_host }}/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA'
      dest: /tmp/virtual-provider-CA.cert
      validate_certs: false
      force: yes

  - name: Obtain SSO token with using username/password credentials
    ovirt_auth:
      ca_file: /tmp/virtual-provider-CA.cert
      url: 'https://{{ virt_provider_host }}/ovirt-engine/api'
      username: '{{ username }}'
      password: '{{ password }}'

  - name: Create vm
    ovirt_vms:
      auth: '{{ ovirt_auth }}'
      state: present
      name: 'ds-{{ item }}'
      cluster: '{{ virt_provider_cluster }}'
      template: '{{ kube_vm_template }}'
      operating_system: rhel_7x64
      stateless: false
      cloud_init:
        host_name: 'ds-{{ item }}.{{ local_domain }}'
        user_name: '{{ user_name }}'
        root_password: '{{ user_password }}'
    with_items: '{{ hostnames }}'
