---
# tasks file for docker
- name: Check Docker Registry Config view NEW WAY
  stat: path=/etc/containers/registries.conf
  register: docker_registry_new_way

- name: Setup Docker Insceure Registry OLD WAY
  lineinfile:
    name: /etc/sysconfig/docker
    regexp: '^ADD_REGISTRY='
    line: ADD_REGISTRY='--add-registry {{ satellite_host }}:5000'
  when: satellite_host != '' and docker_registry_new_way.stat.exists == False
  notify:
  - docker_restart

- name: Setup Docker Insceure Registry NEW WAY
  blockinfile:
    name: /etc/containers/registries.conf
    block: |
      registries:
        - registry.access.redhat.com
        - {{ satellite_host }}:5000
      insecure_registries:
        - {{ satellite_host }}:5000
  when: satellite_host != '' and docker_registry_new_way.stat.exists == True
  notify:
  - docker_restart

- name: Pull Kubernetes Docker Images from Local Satellite Registry
  docker_image:
    name: '{{ satellite_host }}:5000/{{ docker_images_prefix }}{{ item }}'
  with_items: '{{ kube_images }}'
  when: satellite_host != ''

- name: Pull Application Docker Images from Local Satellite Registry
  docker_image:
    name: '{{ satellite_host }}:5000/{{ docker_images_prefix }}{{ item }}'
  with_items: 
  - '{{ eap_image }}'
  - '{{ postgres_image }}'
  when: satellite_host != ''

- name: Pull Kubernetes Docker Images from Red Hat Registry
  docker_image:
    name: 'rhel7/{{ item }}'
  with_items: '{{ kube_images }}'
  when: satellite_host == ''

- name: Pull Application Docker Images from Red Hat Registry
  docker_image:
    name: '{{ item }}'
  with_items: 
  - 'jboss-eap-7/{{ eap_image }}'
  - 'rhcl/{{ postgres_image }}'
  when: satellite_host == ''
